### ISSUE TITLE
mat4 x vec4 mult strange behaviours

### ISSUE THREAD

**Issue by pepcots** [mackst/glm#4]
mat4 x vec4 return strange behaviours on Y component (it's inverted)
```
translate( mat4(), vec3(1,1,1)) * vec4(1,1,1,1)
array('f', [2.0, 0.0, 2.0, 1.0])
```

but it should return [2, 2, 2]

**Comment by mackst** [comment]
Yeah it's a bug. Fixed

**Comment by pepcots** [comment]
Some years later... but thanks!! I've used you library in many peojects.
